### ISSUE TITLE
Creating strand within spawned coroutine

### ISSUE THREAD

**Issue by assafcohen** [chriskohlhoff/asio#1357]
Hi,
Thank you for this amazing library.
I have a situation where I am running in spawned coroutines, that was co_spawned on the same strand.
These coroutines manipulate shared resource, hence the use of strand.
At a certain point in the coroutine there’s a long loop of async operations that doesn’t access the shared resource.
Will it be safe to spawn a new coroutine with a new strand.
And co_await on it?
Thanks again

**Comment by klemens-morgenstern** [comment]
co_spawn would be safe then, yes.

**Comment by assafcohen** [comment]
Thanks

**Comment by assafcohen** [comment]
Reopened with example:

`#include <asio.hpp>

using asio::ip::tcp;
using asio::awaitable;
using asio::use_awaitable;
using asio::detached;
using asio::io_context;
using asio::buffer;

int shared = 0;

awaitable<void> shared_resource_modify_inc(tcp::socket &socket) {
    char data[1024];
    ++shared;
    co_await socket.async_read_some(buffer(data), use_awaitable);
}

awaitable<void> shared_resource_modify_dec(tcp::socket &socket) {
    char data[1024];
    --shared;
    co_await socket.async_read_some(buffer(data), use_awaitable);
}

awaitable<void> no_shared_resource_access(tcp::socket &socket) {
    char data[1024];
    for (;;) {
        auto n = co_await socket.async_read_some(buffer(data), use_awaitable);
        co_await async_write(socket, buffer(data, n), use_awaitable);
    }
}

awaitable<void> handler(io_context &ioContext, tcp::socket socket) {
    co_await shared_resource_modify_inc(socket);
    co_await co_spawn(make_strand(ioContext), no_shared_resource_access(socket), use_awaitable);
    co_await shared_resource_modify_dec(socket);
    
}

awaitable<void> listener(io_context &ioContext) {
    auto executor = co_await asio::this_coro::executor;
    tcp::acceptor acceptor(executor, {tcp::v4(), 55555});
    for (;;) {
        tcp::socket socket = co_await acceptor.async_accept(use_awaitable);
        co_spawn(executor, handler(ioContext, std::move(socket)), detached);
    }
}

int main(int, char *[])
{
    io_context ioContext;
    co_spawn(ioContext, listener(ioContext), detached);
    std::thread t([&ioContext]() {
        ioContext.run();
    });
    ioContext.run();
    t.join();
    return 0;
}
`

1. is it the correct assumption that on handler shared_resource_modify_* will be called on executor( from listener function )?
2.  is it the correct assumption that on handler no_shared_resource_access will be called on newly created strand? and completion of that co_spawned coroutine will be called on executor?
3. if the 2 above are true, is it safe to assume that multithreaded io_context run calls, are thread safe and will have better utilization of cpu ( in the context of completion tokens )?
Thanks

**Comment by klemens-morgenstern** [comment]
1. yes
2. yes. but you actually don't need a strand here. an awaitable like this is an implicit strand. As long as you don't share data, you can co_spawn directly on a multi-threaded executor.
3. No. Multi-threading introduces locking etc., so it might (!) actually be a negative for performance. This heavily depends on your application and you'll need to profile. 
You might be better off using a single-threaded io_context with [BOOST_ASIO_CONCURRENCY_HINT_1](https://www.boost.org/doc/libs/release/doc/html/boost_asio/overview/core/concurrency_hint.html) and a single thread.
My recommendation would be to make this a compile option like so:

```cpp
#if defined(MY_PROJECT_ST) // single threaded mode
auto my_make_strand(asio::io_context & ctx) {return ctx.get_executor();};
#define MY_CONCURRENCY_HINT BOOST_ASIO_CONCURRENCY_HINT_1
#else
auto my_make_strand(asio::io_context & ctx) {return asio::make_strand(ctx);};
#define MY_CONCURRENCY_HINT BOOST_ASIO_CONCURRENCY_HINT_DEFAULT
#endif


// ... in main

asio::io_context ioContext{MY_CONCURRENCY_HINT};
```

And then you can profile this in a much easier way, while just using `my_make_strand` where needed.

My personal opinion is that MT is overused in many asio applications, because many of them are mainly busy waiting for IO. If you do a lot of IO your CPU will be faster then you're networking card, so a single thread will do. I'd start single threaded and only go MT when you exhaust one core with your application.

**Comment by assafcohen** [comment]
Thank you very much
